### PR TITLE
Allow custom role rights, set env, update output

### LINKED ISSUE #6: Use the new set output instead of the deprecated one
Per https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ - output will soon be deprecated, and should be trivial to change (although I don't have any way to validate it).

P.S. You might be interested in my [github action code](https://stackoverflow.com/a/74189534/177275) to install Postgis on Windows -- ideally this could be integrated into your action (together with something for mac & linux) - to make things far simpler.

Thanks for the code!

### LINKED ISSUE #7: New user has no rights, and cannot be changed when default
The createuser command used by this action creates `postgres` user without superuser abilities. This means I cannot do actions like `CREATE EXTENSION` and other critical actions. There may be a need for another parameter for the user access rights.  Thx!

### PR DESCRIPTION
**Pull request by nyurik**
* use new output system
* allow customization of the user rights
* export PGDATABASE and PGPASSWORD env vars

fixes #6
fixes #7

### CODE REVIEW

**Comment by rcmuniz1994** [comment]
@ikalnytskyi This PR fixes a warning about a deprecated command too. See:

Screen Shot 2022-12-15 at 00 03 21

Isn't it interesting merge it asap? Or, if you want, I can fix just part related with the warning.

Thanks. Have a nice day.

**Comment by nyurik** [comment]
@rcmuniz1994 I have since released an updated version that has postgis focus - https://github.com/actions-marketplace-validations/nyurik_action-setup-postgis -- but obviously many people only need postgres itself, not postgis.

**Comment by ikalnytskyi** [comment]
Hey @nyurik,

Thanks for the patch and sorry for ignoring it for so long.

> use new output system

Can you please submit it as a separate PR? If inconvenient, I can do it on your behalf. I just want to track separate changes separately, preserving rationale in commits description.

> export PGDATABASE and PGPASSWORD env vars

Can you please explain why do we need this? Users are advised to use connection-uri instead of relying on environment variables.

> allow customization of the user right

The trick you're doing is a little bit low-level. Can you please explain to me what is your use case and what are you trying to achieve? I'd expect `createuser` invoked by this action to be an implementation detail, and all non-standard users be crafted by action users via `createuser` manual invocation.

**Comment by ikalnytskyi** [comment]
I think raised concerns are addressed in `@v4`, so I'm closing this patch. Please feel free to re-submit with improvements you're still missing or file a ticket in the issue tracker.

**Comment by nyurik** [comment]
@ikalnytskyi thanks for an in-depth reply!  I somehow missed, and only now got back to reviewing all this. Thanks for your dedication!

**Pull request closed without merging**
